map_server:
  ros__parameters:
    yaml_filename: "/home/svr/ROBOMUSE_WS/13_march.yaml"
    topic_name: "map"
    frame_id: map
    odom_frame: odom
    scan_topic: /scan
    use_sim_time: false

map_saver:
  ros__parameters:
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65

costmap_filter_info_server:
  ros__parameters:
    type: 1
    filter_info_topic: "costmap_filter_info"
    mask_topic: "filter_mask"
    base: 0.0
    multiplier: 0.25